name: Build and Release Gradle Project

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build with Gradle
        run: ./gradlew build

      - name: Get current date and time for tag
        id: date
        run: echo "TAG_NAME=$(date -u +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-jar
          path: build/libs/BlueBerryNetworkHelper-v1.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: built-jar
          path: build/libs/

      - name: Get current date and time for tag
        id: date
        run: echo "TAG_NAME=$(date -u +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: List files (debug)
        run: ls -R

      - name: Create Release and Upload JAR
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.TAG_NAME }}
          name: "Release ${{ steps.date.outputs.TAG_NAME }}"
          body: "Automated release created by GitHub Actions"
          draft: false
          prerelease: false
          files: build/libs/BlueBerryNetworkHelper-v1.jar
